apiVersion: v1
kind: Pod
metadata:
  name: demo-app
  labels:
    zone: prod
    version: v1
    app: sleep
spec:
  containers:
  - name: demo-app
    image: venkatce/demo-image:1.0
    ports:
    - containerPort: 80
